changelog:
  exclude:
    labels:
      - ignore-for-release
      # GitHub Actions updates aren't user-facing
      - github_actions
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
